// Mocks generated by Mockito 5.4.6 from annotations
// in untitled5/test/search_polling_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:untitled5/core/models/search_models.dart' as _i2;
import 'package:untitled5/features/search/domain/repositories/search_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSearchResponse_0 extends _i1.SmartFake
    implements _i2.SearchResponse {
  _FakeSearchResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchSessionStatusResponse_1 extends _i1.SmartFake
    implements _i2.SearchSessionStatusResponse {
  _FakeSearchSessionStatusResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAIStatusResponse_2 extends _i1.SmartFake
    implements _i2.AIStatusResponse {
  _FakeAIStatusResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SearchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchRepository extends _i1.Mock implements _i3.SearchRepository {
  MockSearchRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.SearchResponse> search(
    _i2.SearchRequest? request, {
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#search, [request], {#cancelToken: cancelToken}),
            returnValue: _i4.Future<_i2.SearchResponse>.value(
              _FakeSearchResponse_0(
                this,
                Invocation.method(
                  #search,
                  [request],
                  {#cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.SearchResponse>);

  @override
  _i4.Future<_i2.SearchSessionStatusResponse> getSearchStatus(
    String? requestId, {
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getSearchStatus,
              [requestId],
              {#cancelToken: cancelToken},
            ),
            returnValue: _i4.Future<_i2.SearchSessionStatusResponse>.value(
              _FakeSearchSessionStatusResponse_1(
                this,
                Invocation.method(
                  #getSearchStatus,
                  [requestId],
                  {#cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.SearchSessionStatusResponse>);

  @override
  _i4.Future<_i2.AIStatusResponse> getAiStatus(
    String? requestId, {
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getAiStatus,
              [requestId],
              {#cancelToken: cancelToken},
            ),
            returnValue: _i4.Future<_i2.AIStatusResponse>.value(
              _FakeAIStatusResponse_2(
                this,
                Invocation.method(
                  #getAiStatus,
                  [requestId],
                  {#cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.AIStatusResponse>);

  @override
  _i4.Future<List<_i2.Country>> getCountries() =>
      (super.noSuchMethod(
            Invocation.method(#getCountries, []),
            returnValue: _i4.Future<List<_i2.Country>>.value(<_i2.Country>[]),
          )
          as _i4.Future<List<_i2.Country>>);

  @override
  _i4.Future<List<_i2.Store>> getStores(
    String? country, {
    String? q,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getStores, [country], {#q: q, #limit: limit}),
            returnValue: _i4.Future<List<_i2.Store>>.value(<_i2.Store>[]),
          )
          as _i4.Future<List<_i2.Store>>);

  @override
  _i4.Future<String> scanBarcode(_i2.BarcodeRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#scanBarcode, [request]),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#scanBarcode, [request]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> recognizeImage(_i2.ImageRecognitionRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#recognizeImage, [request]),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#recognizeImage, [request]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<_i2.SearchResponse> analyzeProduct(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeProduct, [data]),
            returnValue: _i4.Future<_i2.SearchResponse>.value(
              _FakeSearchResponse_0(
                this,
                Invocation.method(#analyzeProduct, [data]),
              ),
            ),
          )
          as _i4.Future<_i2.SearchResponse>);
}
